language: cpp
os:
- linux
- osx
dist: trusty
compiler:
- clang
- gcc
sudo: required
branches:
  only:
    - travis
before_install:
- chmod +x dist/travis/*.sh
- dist/travis/before_script.sh
script:
- sh -x dist/travis/script.sh
